import tracemalloc
import psycopg2
from urllib.parse import quote_plus
from services.clients import supabase
from services.stocks.nse_fetcher import get_kite_instruments

tracemalloc.start()

DB_URI = f"postgresql://postgres:{quote_plus('Howstrongthepasswordcanbe')}@db.ivyrhbzhefpqaxngedrk.supabase.co:6543/postgres"

INSTRUMENT_DB_MAP = {
    "instrument_token": "instrument_token",
    "exchange_token": "exchange_token",
    "tradingsymbol": "symbol",
    "name": "company_name",
    "instrument_type": "instrument_type",
    "exchange": "exchange"
}

def create_supabase_table(exchange: str):  
    commands = (
        f"""
        CREATE TABLE IF NOT EXISTS public.{exchange}_stocks (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instrument_token NUMERIC(20, 0) NOT NULL UNIQUE,
            symbol TEXT NOT NULL,
            company_name TEXT NOT NULL,
            exchange TEXT NOT NULL,
            instrument_type TEXT,
            exchange_token TEXT
        );
        """,
    )
    
    conn = None
    try:
        conn = psycopg2.connect(DB_URI)
        cur = conn.cursor()
        
        for command in commands:
            cur.execute(command)
            
        cur.close()
        conn.commit()
        print("Table and indexes created successfully in Supabase!")
        
    except (Exception, psycopg2.DatabaseError) as error:
        print(f"Error executing SQL: {error}")
    finally:
        if conn is not None:
            conn.close()


def fetch_and_insert_instruments(exchange, offset=150, limit=250):
    print('called')
    instruments = get_kite_instruments()
    
    formatted_instruments = []
    for instrument in instruments:
        formatted_instrument = {db_col: instrument.get(kite_col, '') for kite_col, db_col in INSTRUMENT_DB_MAP.items()}
        formatted_instruments.append(formatted_instrument)

    try:
        response = supabase.table(f"{exchange.lower()}_stocks").insert(formatted_instruments).execute()
        print(f"Inserted {len(formatted_instruments)} records into Supabase for {exchange}")
        return fetch_stocks_from_supabase(exchange, offset, limit)
    except Exception as e:
        print(f"Error inserting into Supabase: {e}")
  
def fetch_stocks_from_supabase(exchange: str, offset, limit):
    table_name = f"{exchange.lower()}_stocks"
    query = f"""SELECT 1 FROM information_schema.tables 
    WHERE table_schema = 'public' AND table_name = '{table_name}'
    """
    try:
        while True:
            resp = (
                supabase.table(table_name)
                .select("*")
                .range(offset, offset + limit - 1)
                .execute()
            )
            batch = resp.data
            if not batch:
                return fetch_and_insert_instruments(exchange, offset, limit)
            return {"stocks": batch}
    except (Exception, psycopg2.DatabaseError) as error:
        print(f"Error checking table existence: {error}")
        return fetch_and_insert_instruments(exchange, offset, limit)

    


